services:
  - type: web
    name: meta-betties-frontend
    env: node
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm ci --legacy-peer-deps
      npm install @solana-mobile/wallet-adapter-mobile@1.0.1 --save --legacy-peer-deps
      npm install cross-env --save --legacy-peer-deps
      npm run build:render
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://api-server-wcjc.onrender.com
      - key: NODE_VERSION
        value: "18.17.0"
    healthCheckPath: /
    autoDeploy: true 