services:
  - type: web
    name: nft-verification-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://api-server-wcjc.onrender.com
    healthCheckPath: /
    autoDeploy: true
