services:
  - type: web
    name: meta-betties-frontend
    env: node
    buildCommand: |
      npm ci --legacy-peer-deps
      npm install @solana-mobile/wallet-adapter-mobile@^0.4.0
      npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://api-server-wcjc.onrender.com
      - key: NODE_VERSION
        value: "18.17.0"
    healthCheckPath: /
    autoDeploy: true 
